# Generated by Django 5.2.8 on 2025-12-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
