# Generated by Django 5.2.8 on 2025-12-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaiapp', '0003_chaicertificate_chaireview_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaicertificate',
            old_name='valid_untill',
            new_name='valid_until',
        ),
    ]
